local_costmap:
  inflation_layer:
    enabled: true # defaults to true
    cost_scaling_factor:  5  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.3  # max. distance from an obstacle at which costs are incurred for planning paths. (default: 0.5)

DWAPlannerROS:
  xy_goal_tolerance: 0.15 # defaults to 0.15
  yaw_goal_tolerance: 0.3
  min_in_place_vel_theta: 0.8
  occdist_scale: 0.2            # 0.5   - weighting for how much the controller should avoid obstacles

  # Robot Configuration Parameters - Kobuki
  max_vel_x: 0.5  # 0.55
  min_vel_x: 0.0 

  max_vel_y: 0.0  # diff drive robot
  min_vel_y: 0.0  # diff drive robot

  max_trans_vel: 0.5 # choose slightly less than the base's capability
  min_trans_vel: 0.1  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.1

  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.

  max_rot_vel: 5.0  # choose slightly less than the base's capability
  min_rot_vel: 0.4  # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.4
  
  acc_lim_x: 1.0 # maximum is theoretically 2.0, but we 
  acc_lim_theta: 2.0
  acc_lim_y: 0.0      # diff drive robot


obstacle_layer:
  track_unknown_space: true

robot_radius: 0.18 # Defaults to 0.20. Koboki is 0.18