controller_manager:
  plugin: custom_controller_manager/CustomControllerManager
controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_7
      - joint_8
  - name: virtual_controller
    type: $(arg fake_execution_type)
    joints:
      - virtual_joint
      - virtual_joint_x
      - virtual_joint_y
      - virtual_joint_theta
      
initial:  # Define initial robot poses.
  - group: arm_group
    pose: zero